# ML Project_1
# Title

Credit Risk Analysis using Machine Learning

# objective

Build a machine learning model to predict whether a customer is a credit risk or not based on their financial and personal information.

# Problem Statement
Financial institutions face significant losses due to loan defaults. The goal of this project is to develop a classification model that can predict whether a loan applicant is likely to be a “Risk” or “Not Risk” before approving the loan.

# Business Use Case
Help banks reduce bad loans (NPAs)

Improve loan approval decisions

Minimize financial risk

Automate credit evaluation process

In [ ]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# ML
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

import warnings
# Example: ignore all warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv("/content/clean_data.csv")

print(df.shape)
df.head()

(9709, 20)

,ID,Gender,Own_car,Own_property,Work_phone,Phone,Email,Unemployed,Num_children,Num_family,Account_length,Total_income,Age,Years_employed,Income_type,Education_type,Family_status,Housing_type,Occupation_type,Target
0,5008804,1,1,1,1,0,0,0,0,2,15,427500.0,32.868574,12.435574,Working,Higher education,Civil marriage,Rented apartment,Other,1
1,5008806,1,1,1,0,0,0,0,0,2,29,112500.0,58.793815,3.104787,Working,Secondary / secondary special,Married,House / apartment,Security staff,0
2,5008808,0,0,1,0,1,1,0,0,1,4,270000.0,52.321403,8.353354,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,Sales staff,0
3,5008812,0,0,1,0,0,0,1,0,1,20,283500.0,61.504343,0.000000,Pensioner,Higher education,Separated,House / apartment,Other,0
4,5008815,1,1,1,1,1,1,0,0,2,5,270000.0,46.193967,2.105450,Working,Higher education,Married,House / apartment,Accountants,0

In [ ]:
df.isnull().sum()

ID                 0
Gender             0
Own_car            0
Own_property       0
Work_phone         0
Phone              0
Email              0
Unemployed         0
Num_children       0
Num_family         0
Account_length     0
Total_income       0
Age                0
Years_employed     0
Income_type        0
Education_type     0
Family_status      0
Housing_type       0
Occupation_type    0
Target             0
dtype: int64

In [ ]:
X = df.drop("Target", axis=1)
y = df["Target"]

In [ ]:
X.dtypes

ID                   int64
Gender               int64
Own_car              int64
Own_property         int64
Work_phone           int64
Phone                int64
Email                int64
Unemployed           int64
Num_children         int64
Num_family           int64
Account_length       int64
Total_income       float64
Age                float64
Years_employed     float64
Income_type         object
Education_type      object
Family_status       object
Housing_type        object
Occupation_type     object
dtype: object

In [ ]:
# check how many columns are categorical
for i in X.columns:
    if X[i].dtype == 'object':
        print(i)

Income_type
Education_type
Family_status
Housing_type
Occupation_type

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col])
X

,ID,Gender,Own_car,Own_property,Work_phone,Phone,Email,Unemployed,Num_children,Num_family,Account_length,Total_income,Age,Years_employed,Income_type,Education_type,Family_status,Housing_type,Occupation_type
0,5008804,1,1,1,1,0,0,0,0,2,15,427500.0,32.868574,12.435574,4,1,0,4,12
1,5008806,1,1,1,0,0,0,0,0,2,29,112500.0,58.793815,3.104787,4,4,1,1,17
2,5008808,0,0,1,0,1,1,0,0,1,4,270000.0,52.321403,8.353354,0,4,3,1,15
3,5008812,0,0,1,0,0,0,1,0,1,20,283500.0,61.504343,0.000000,1,1,2,1,12
4,5008815,1,1,1,1,1,1,0,0,2,5,270000.0,46.193967,2.105450,4,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9704,5148694,0,0,0,0,0,0,0,0,2,20,180000.0,56.400884,0.542106,1,4,0,2,8
9705,5149055,0,0,1,1,1,0,0,0,2,19,112500.0,43.360233,7.375921,0,4,1,1,12
9706,5149729,1,1,1,0,0,0,0,0,2,21,90000.0,52.296762,4.711938,4,4,1,1,12
9707,5149838,0,0,1,0,1,1,0,0,2,32,157500.0,33.914454,3.627727,1,1,1,1,11
9708,5150337,1,0,1,0,0,0,0,0,1,13,112500.0,25.155890,3.266323,4,4,3,4,8

In [ ]:
# check how many columns are categorical
for i in X.columns:
    if X[i].dtype == 'object':
        print(i)

# Feature selection
Best method for your dataset = Embedded (SelectFromModel)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
#Pipelines with StandardScaler
from sklearn.preprocessing import StandardScaler, MinMaxScaler
pipelines_std = {
    "LR_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression())]),

    "RF_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", RandomForestClassifier(n_estimators=100, random_state=42))]),

    "SVM_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC())]),

    "GB_Std": Pipeline([
        ("scaler", StandardScaler()),
        ("model", GradientBoostingClassifier())])}

In [ ]:
#Pipelines with MinMaxScaler
pipelines_minmax = {
    "LR_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", LogisticRegression(max_iter=1000))]),

    "RF_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", RandomForestClassifier(n_estimators=100, random_state=42))]),

    "SVM_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", SVC())]),

    "GB_MinMax": Pipeline([
        ("scaler", MinMaxScaler()),
        ("model", GradientBoostingClassifier())])}

In [ ]:
#4: Train & Evaluate All Models

from sklearn.metrics import accuracy_score

results = {}

# Combine both pipeline sets
all_pipelines = {**pipelines_std, **pipelines_minmax}

for name, pipe in all_pipelines.items():
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    results[name] = acc

    print(f"{name} → Accuracy: {acc}")

LR_Std → Accuracy: 0.8542739443872297
RF_Std → Accuracy: 0.8553038105046344
SVM_Std → Accuracy: 0.8542739443872297
GB_Std → Accuracy: 0.854788877445932
LR_MinMax → Accuracy: 0.8542739443872297
RF_MinMax → Accuracy: 0.8553038105046344
SVM_MinMax → Accuracy: 0.8542739443872297
GB_MinMax → Accuracy: 0.8542739443872297

In [ ]:
import pandas as pd

result_df = pd.DataFrame(list(results.items()), columns=["Model", "Accuracy"])
print(result_df)

        Model  Accuracy
0      LR_Std  0.854274
1      RF_Std  0.855304
2     SVM_Std  0.854274
3      GB_Std  0.854789
4   LR_MinMax  0.854274
5   RF_MinMax  0.855304
6  SVM_MinMax  0.854274
7   GB_MinMax  0.854274

In [ ]:
A=0
for i,j in results.items():
  if A<=j:
    A=j
print(A)
for i,j in results.items():
  if j==A:
    print(i,j)

0.8553038105046344
RF_Std 0.8553038105046344
RF_MinMax 0.8553038105046344

Interview Answer

“I built multiple pipelines using both StandardScaler and MinMaxScaler with different classification models. I evaluated them using accuracy and selected the best-performing combination.”

Hyperparameter tuning in Random Forest focuses on optimizing parameters like the number of trees, maximum depth, and feature selection to balance accuracy, generalization, and computational efficiency. The most impactful parameters are n_estimators, max_depth, max_features, and min_samples_split.

# - Grid Search
- Try all combinations of parameters.

#Use Cross-Validation (Better than single accuracy)

Why this is better?
Uses full dataset ,
Reduces overfitting ,
Gives stable performance

🔥 What This Code Does

✔ Tries multiple models
✔ Uses cross-validation (cv=5)
✔ Compares average accuracy
✔ Automatically selects best model

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200, 500,1000],
    'max_depth': [5, 10, 20],
 #   'max_features': ['sqrt', 'log2'],
 #   'min_samples_split': [2, 5, 10]
    }

Final_model = GridSearchCV(RandomForestClassifier(), param_grid, cv=5)
Final_model.fit(X_train, y_train)
print(Final_model.best_params_)

{'max_depth': 5, 'n_estimators': 100}

In [ ]:
# Final Model testing
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

y_pred = Final_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 0.8542739443872297
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1659
           1       0.00      0.00      0.00       283

    accuracy                           0.85      1942
   macro avg       0.43      0.50      0.46      1942
weighted avg       0.73      0.85      0.79      1942

[[1659    0]
 [ 283    0]]

In [ ]:
from collections import Counter
Counter(y)

Counter({1: 1283, 0: 8426})

In [ ]:
# Balancing the class
from imblearn.over_sampling import RandomOverSampler
# Apply Oversampling
rus = RandomOverSampler()
X1,Y1 = rus.fit_resample(X, y)

print(Counter(Y1))

Counter({1: 8426, 0: 8426})

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X1,Y1, test_size=0.2, random_state=42)

In [ ]:
param_grid = {
    'n_estimators': [100,200, 500],
    'max_depth': [ 10, 20],
 #   'max_features': ['sqrt', 'log2'],
 #   'min_samples_split': [2, 5, 10]
    }

best_model = GridSearchCV(RandomForestClassifier(), param_grid, cv=5)
best_model.fit(X_train, y_train)
print(best_model.best_params_)

{'max_depth': 20, 'n_estimators': 200}

In [ ]:
y_pred2 = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred2))
print(classification_report(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

Test Accuracy: 0.9916938593889054
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      1680
           1       0.99      1.00      0.99      1691

    accuracy                           0.99      3371
   macro avg       0.99      0.99      0.99      3371
weighted avg       0.99      0.99      0.99      3371

[[1657   23]
 [   5 1686]]

# FINAL INTERVIEW ANSWER
I tuned n_estimators between 100–500, max_depth between 10–50, and max_features as sqrt or log2. I used RandomizedSearchCV to quickly identify promising ranges, then refined with GridSearchCV. This improved accuracy by around 14% while keeping training time manageable.

In [ ]:
# Hyperparameter tuning LogisticRegression

pipe_lr = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))])
param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100],
    "model__penalty": ["l1", "l2"],
    "model__solver": ["liblinear", "saga"],
    'model__class_weight': ['balanced', None]}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(
    pipe_lr,
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1)

grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Params: {'model__C': 0.01, 'model__class_weight': None, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
Best CV Score: 0.8712501481335995

FINAL INTERVIEW ANSWER

“I optimized Logistic Regression using GridSearchCV by tuning regularization strength (C), penalty type, and solver. I evaluated the model using cross-validation and selected the best configuration based on accuracy and ROC-AUC score.”

A sequence of data transformers with an optional final predictor.

`Pipeline` allows you to sequentially apply a list of transformers to
preprocess the data and, if desired, conclude the sequence with a final
:term:`predictor` for predictive modeling.

In [ ]:
# Final Model
best_model = grid.best_estimator_
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 0.8542739443872297
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1659
           1       0.00      0.00      0.00       283

    accuracy                           0.85      1942
   macro avg       0.43      0.50      0.46      1942
weighted avg       0.73      0.85      0.79      1942

[[1659    0]
 [ 283    0]]

In [ ]:
from sklearn.metrics import roc_auc_score

y_prob = best_model.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_prob))

ROC-AUC: 0.5589013348328105

“I optimized Logistic Regression using GridSearchCV by tuning regularization strength (C), penalty type, and solver. I evaluated the model using cross-validation and selected the best configuration based on accuracy and ROC-AUC score.”

In [ ]:
# Hyperparameter tuning for SVC

from sklearn.model_selection import GridSearchCV
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly']
    }

# Step 3: GridSearchCV (Tests 4×3×5×2 = 120 combinations!)
grid_search = GridSearchCV(
    SVC(),
    param_grid,
    cv=5,
    scoring='accuracy')
grid_search.fit(X_train, y_train)

In [ ]:
best_model = grid_search.best_estimator_
best_model